# Generated by Django 5.2.10 on 2026-01-20 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_turf_latitude_turf_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
