# Generated by Django 5.2.10 on 2026-01-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_otp_token_alter_otp_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='game_type',
            field=models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('badminton', 'Badminton'), ('tennis', 'Tennis')], default='cricket', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ground',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
