# Generated by Django 5.2.10 on 2026-01-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_adminotp_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminotp',
            name='email',
            field=models.EmailField(default='temp@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
