# Generated by Django 5.2.10 on 2026-02-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_adminotp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='turf_images/'),
        ),
    ]
